services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --log.level=warn
    ports:
      - 9090:9090
    networks:
      - prom_net
    restart: unless-stopped

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    volumes:
      - ./config/alertmanager:/etc/alertmanager
    command: 
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --log.level=warn
    ports:
      - 9093:9093
    networks:
      - prom_net
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - ./config/grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - GF_DEFAULT_INSTANCE_NAME=${INSTANCE_NAME}
      - GF_SERVER_DOMAIN=${INSTANCE_NAME}
      - GF_SERVER_ROOT_URL=http://${INSTANCE_NAME}/
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_IGNORE_HTTPS_ERRORS=true
      - GF_SMTP_ENABLED=false
      - GF_SMTP_SKIP_VERIFY=true
      # - GF_SMTP_HOST=${SMTP_HOST}
      # - GF_SMTP_EHLO_IDENTITY=${SMTP_EHLO_IDENTITY}
      # - GF_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/node-exporter-full.json
      - GF_LOG_LEVEL=warn
    ports:
      - 3000:3000
    networks:
      - prom_net
    restart: unless-stopped

  telegraf:
    container_name: telegraf
    image: telegraf:1.28.1
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - 9273:9273
    networks:
      - prom_net
    restart: unless-stopped

volumes:
  prometheus-data:
networks:
  prom_net:
