{
 "title": "MAIN",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Balances",
   "type": "stat",
   "gridPos": { "h": 20, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "р." } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "provider1_balance", "legendFormat": "provider1" },
    {
     "expr": "provider2_balances_values_sum / 100",
     "legendFormat": "provider2"
    }
   ]
  },
  {
   "title": "Services Status",
   "type": "stat",
   "gridPos": { "h": 20, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_response_http_response_code{job=\"telegraf\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 20, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs',fstype!~\"tmpfs\"})",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "stat",
   "gridPos": { "h": 20, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs',fstype!~\"tmpfs\"} /1024 /1024 /1024",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  }
 ]
}