global:
  scrape_interval: 1m
  scrape_timeout: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - alerts.yml
  - prometheus-alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: 'node'
    static_configs:
      - targets: [
                  'host1.company.name:9100',
                  'host2.company.name:9100',
                  'host3.company.name:9100',
                  'pg.company.name:9100']

  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']
